sudo: false

git:
  depth: 3

branches:
  only:
    - next
    - master

language: node_js

cache:
  npm: true

stages:
  - test

jobs:
  include:
    # - stage: lint ✨
    #   script: npm run lint
    #   node_js: lts/*

    - stage: test 👩🏽‍💻
      script: npm run test:cov
      node_js: node
    - node_js: lts/*
    # - os: windows
    #   node_js: node
    # - os: windows
    #   node_js: lts/*
