sudo: false

git:
  depth: 3

branches:
  only:
    - next
    - master

language: node_js

os:
  - linux
  # - windows

cache:
  npm: true

stages:
  - test

jobs:
  include:
    # - stage: lint ✨
    #   script: npm run lint

    - stage: test 👩🏽‍💻
      script: npm run test:cov
      node_js: node
    - node_js: lts/*
